name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  construir:

    runs-on: ubuntu-24.04

    steps:
      - name: Pull Repositorio
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t kiriloo/calculadora:$(date +%s) .

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
